### ISSUE TITLE
Is that  work for php7.2

### ISSUE THREAD

**Issue by havefive** [bailoo/itrack#70]
$connection = ssh2_connect('111.118.182.147', 22);
ssh2_auth_password($connection, 'root', 'HHYDHN@146#53');
$tunnel = ssh2_tunnel($connection, '111.118.182.147', 3306);
$DbConnection = new mysqli_connect('111.118.182.147', 'root', 'mysql',  'test_db', 3306, $tunnel) or die ('Fail: '.mysql_error());
echo "<br>DbCon=".$DbConnection;

**Comment by bailoo** [comment]
I am not sure, this code has not been tested on 7.2
